server:
  rootPath: /api/v1/
swagger:
  resourcePackage: io.mmc.domain
mongoConnectionUri: ${MONGO_DB_CONNECTION_URI}
redis:
  host: ${REDIS_HOSTNAME}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}